### PR TITLE
Explicitly set stringsAsFactors = TRUE in tests. #166

### PR DESCRIPTION
**Pull request by ateucher**
This is a fix for #166, just by setting `stringsAsFactors = TRUE` in the test. We could also expose `stringsAsFactors` in [`topojson_read()`](https://github.com/ropensci/geojsonio/blob/b850ff600d4f1932c7198fd5583d983a1bc1e117/R/topojson_read.R) (default `FALSE`), which might be friendly to users? It can currently be set in `...` and sent through to to `sf::st_read()`.

### CODE REVIEW

**Comment by sckott** [comment]
looks like you're still tweaking things, let me know when you're good to go

**Comment by ateucher** [comment]
@sckott finally all passing if you want to have a look. Pretty messy commits, so probably want to squash them!

**Comment by sckott** [comment]
Okay, thanks, having a look

**Comment by sckott** [comment]
thanks so much for sorting this out

**Pull request merged**
