### PR TITLE
Allow setting precision of coordinates in geojson_write

### PR DESCRIPTION
**Pull request by ateucher**
I don't think this is ready for merging yet - I haven't written any tests, or even manually tried all the methods, but thought I would put it out there to see what you think.

`ogr2ogr` by default seems to put a ridiculous amount of precision in the coordinates when creating GeoJSON, which can make file sizes unnecessarily large. There is a COORDINATE_PRECISION argument to `ogr2ogr` which allows you to set the number of decimal places in the coordinates.

This PR adds a `precision` argument to `write_ogr`, `write_geojson` and all `geojson_write` methods which use those functions.

For example:
```r
poly <- list(c(-114.345703125,39.436192999314095),
          c(-114.345703125,43.45291889355468),
          c(-106.61132812499999,43.45291889355468),
          c(-106.61132812499999,39.436192999314095),
          c(-114.345703125,39.436192999314095))
geojson_write(poly, file = "foo.geojson", geometry = "polygon")
geojson_write(poly, file = "foo2.geojson", geometry = "polygon", precision = 2)
# Look at the first line of coordinates
readLines("foo.geojson", n = 5)[5]
readLines("foo2.geojson", n = 5)[5]
file.info("foo.geojson")["size"]
file.info("foo2.geojson")["size"]
```
capture

### CODE REVIEW

**Comment by ateucher** [comment]
Note: this could already be achieved already by a user passing `layer_options = "COORDINATE_PRECISION=n"` to `...` in `geojson_write()`, so this might be entirely unnecessary
 eg.:

```r
geojson_write(poly, file = "foo.geojson", 
              layer_options = "COORDINATE_PRECISION=2")
```

But it might be nice to highlight in the docs at least...

**Comment by sckott** [comment]
hi @ateucher 

Nice!  Right, users can pass in options to `writeOGR` - but I think it does make sense to abstract out common options that users  may want frequently, instead of forcing them to look up those options in the `rgdal` docs themselves. But make it flexible enough that if they pass in `geojsonio` options they can be combined with any `rgdal` style options

**Comment by ateucher** [comment]
Cool. Yeah, I did think about that. Will have to work that into `write_ogr` for `layer_options`, as well as `dataset_options`, which is currently hard-coded as `dataset_options = "WRITE_BBOX=YES"`. 
I'll work on this (can't promise fast timelines though!)

**Comment by sckott** [comment]
Okay, thanks @ateucher !

**Comment by sckott** [comment]
@ateucher i forget where we're at - you're still going to add more commits, right?

**Comment by ateucher** [comment]
Yup - I think the functionality is there, but should add a test or two. (I know, I should write tests firsts, but I'm not that disciplined) ;)

**Comment by sckott** [comment]
do you mean `yup = you're doing more`, or `yup - it's good to merge` ?

**Comment by ateucher** [comment]
Yup, I'm doing more

**Comment by sckott** [comment]
@ateucher can you change file names in the `R/` dir from lowercase `.r` to uppercase `.R`? that way fewer file changes need to be merged

**Comment by ateucher** [comment]
Can do. Did I do that??

**Comment by sckott** [comment]
@ateucher not sure what's going on, I guess i started out with lowercase `.r`, then changed to all uppercase, but git for some reason still only considers 

ah, i guess because git's by default not case sensitive to file extensions http://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

**Comment by ateucher** [comment]
Ah, gotcha. and my fork still has lowercase.

**Comment by ateucher** [comment]
@sckott for testing this functionality, should I just add to the existing `geojson_write` tests, or should I write some tests directly for `write_geojson` and/or `write_ogr`?

**Comment by sckott** [comment]
hey @ateucher - hmmm, I think for `geojson_write`, but if it makes sense to test the others, do that too

**Comment by ateucher** [comment]
Ok, thanks. `geojson_write` doesn't have any explicit tests yet - they're kind of implicitly tested with the `as.json` tests ... if it works for you I'll create a new test file for `geojson_write` and write some minimal tests to test the new precision functionality - and leave it to you to flesh out as need be? (just being realistic on my time at the moment and it would be nice to get this merged sooner or later).

**Comment by sckott** [comment]
@ateucher ah, forgot there wasn't any tests yet. Yes, thanks for creating a new test file.  yes, just do a minimal set of tests, then we'll get this merged!

**Comment by ateucher** [comment]
:+1:  awesome

**Comment by ateucher** [comment]
Ok @sckott if you want to have a look at the tests, it's probably ready for merge once the Travis build passes.

**Comment by ateucher** [comment]
Or not...

**Comment by ateucher** [comment]
The tests pass on my windows machine... It looks like maybe on Windows only the coordinates are output to the specified precision, whereas on Linux all fields are...

**Comment by sckott** [comment]
i'll take a look

**Comment by ateucher** [comment]
Thanks

**Comment by sckott** [comment]
@ateucher havne't figured it out yet.  okay if I merge, then use `skip_on_travis()` until it's sorted?

**Comment by ateucher** [comment]
Yep, fine with me

**Comment by sckott** [comment]
k, will do

**Pull request merged**
