### PR TITLE
Read url

### PR DESCRIPTION
**Pull request by ateucher**
Not finished, so don't merge yet.  Just opening to let you know I've started on a fix for #91.

I've used `download.file`, but do you think it would be better to use `httr::GET` as in `file_to_geojson` @sckott?

### CODE REVIEW

**Comment by sckott** [comment]
I've seen problems on windows sometimes with `download.file`. Better to use `httr::GET`, and `httr::write_disk` to tempfile I think

**Comment by ateucher** [comment]
Ok will do

**Comment by sckott** [comment]
@ateucher  all done ?

**Comment by ateucher** [comment]
I think so - was going to add a couple more tests though. Also, I reworked the `handle_remote` function to be used for any remote file (not just zips) - need to check the implications of this for `file_to_geojson`

**Comment by sckott** [comment]
> need to check the implications of this for `file_to_geojson`

maybe add test for that?

**Comment by ateucher** [comment]
Yep, for sure. Though I think I probably need to add some specific handling for zip files.

**Comment by sckott** [comment]
thanks

**Comment by sckott** [comment]
looks good @ateucher - all set?

**Comment by ateucher** [comment]
Should be now (as long as the build passes)

**Comment by ateucher** [comment]
The Travis build for the PR seems to be hung up (hasn't started even on the commits I added last night) - https://travis-ci.org/ropensci/geojsonio/pull_requests.

**Comment by sckott** [comment]
Sorry, started a round of builds across most of our pkgs this morning :(

**Comment by sckott** [comment]
canceled some other builds, should start soonish

**Pull request merged**
